# Generated by Django 3.2.25 on 2025-09-24 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPlanner',
            fields=[
                ('content_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_keyword', models.CharField(max_length=2048)),
                ('secondary_keywords', djongo.models.fields.JSONField(blank=True, default=list)),
                ('country_name', models.CharField(max_length=50)),
                ('region_name', models.CharField(max_length=50)),
                ('region_code', models.CharField(max_length=4)),
                ('score', models.TextField(blank=True, default='0', null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('nlp_stats', djongo.models.fields.JSONField(blank=True, default=list)),
                ('track_status', models.TextField(choices=[('INIT', 'Initialized'), ('SCHD', 'Scheduled'), ('DONE', 'Completed'), ('FAIL', 'Failed')], default='INIT', max_length=4)),
                ('track_message', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_planner',
            },
        ),
    ]
