# Generated by Django 3.2.25 on 2026-09-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanager', '0002_contentplanner_fk_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentplanner',
            name='gen_claim_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentplanner',
            name='gen_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentplanner',
            name='gen_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentplanner',
            name='gen_status',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
