# Generated by Django 3.2.25 on 2025-09-24 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_group_name', models.CharField(max_length=100)),
                ('cp_domain_name', models.CharField(max_length=500, null=True)),
                ('cp_grp_trigger', models.CharField(default='DONE', max_length=5)),
                ('cp_total_keyword', djongo.models.fields.JSONField(blank=True, default=[])),
                ('cp_top_score', models.CharField(max_length=10, null=True)),
                ('mn_top_score', models.CharField(max_length=10, null=True)),
                ('cp_activity_level', djongo.models.fields.JSONField(blank=True, default=[])),
                ('mn_activity_level', djongo.models.fields.JSONField(blank=True, default=[])),
                ('cp_since_position', djongo.models.fields.JSONField(blank=True, default=[])),
                ('mn_since_position', djongo.models.fields.JSONField(blank=True, default=[])),
                ('cp_score_meter', djongo.models.fields.JSONField(blank=True, default=[])),
                ('mn_score_meter', djongo.models.fields.JSONField(blank=True, default=[])),
                ('group_call_status', models.CharField(default='COMP', max_length=5)),
                ('keyword_ids', djongo.models.fields.JSONField(blank=True, default=[])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('fk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serp.groups')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competitor_project',
            },
        ),
        migrations.CreateModel(
            name='CompKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_site_url', models.TextField()),
                ('target', models.TextField(null=True)),
                ('rank', djongo.models.fields.JSONField(blank=True, default=[])),
                ('ranknow', models.IntegerField(default=0)),
                ('rank_sincestart', models.IntegerField(default=0)),
                ('featured_snippet', models.BooleanField(default=0)),
                ('review', models.BooleanField(default=0)),
                ('knowledge_panel', models.BooleanField(default=0)),
                ('ads', models.BooleanField(default=0)),
                ('total_rating', models.CharField(blank=True, default=None, max_length=5)),
                ('total_review', models.CharField(blank=True, default=None, max_length=15)),
                ('snippets_details', djongo.models.fields.JSONField(default={})),
                ('dayval', models.IntegerField(default=0)),
                ('weekval', models.IntegerField(default=0)),
                ('halfmonthval', models.IntegerField(default=0)),
                ('daymark', models.CharField(default='-', max_length=5)),
                ('weekmark', models.CharField(default='-', max_length=5)),
                ('halfmonthmark', models.CharField(default='-', max_length=5)),
                ('status_from_start', models.CharField(default='-', max_length=5)),
                ('comp_call_mode', models.CharField(default='done', max_length=5)),
                ('auto_call_status', models.CharField(default='done', max_length=5)),
                ('top_rank', models.IntegerField(default=0)),
                ('lastranked_date', models.DateTimeField()),
                ('comp_call_status', models.BooleanField(default=0)),
                ('platform', models.CharField(default='desktop', max_length=10)),
                ('language_code', models.CharField(max_length=8, null=True)),
                ('isocode', models.CharField(default='us', max_length=5)),
                ('keyword', models.TextField(default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fk_cp_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitor.compproject')),
                ('fk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serp.groups')),
                ('fk_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serp.keyword')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competitor_keyword',
            },
        ),
    ]
