# Generated by Django 3.2.25 on 2025-09-24 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_featured_snippet_date', models.DateTimeField(blank=True)),
                ('featured_snippet_url_list', djongo.models.fields.JSONField(blank=True, default=[])),
                ('featured_snippet_history', djongo.models.fields.JSONField(default={})),
                ('new_ad_snippet_date', models.DateTimeField(blank=True)),
                ('ad_snippet_url_list', djongo.models.fields.JSONField(blank=True, default=[])),
                ('ad_snippet_history', djongo.models.fields.JSONField(default={})),
                ('comp_today', djongo.models.fields.JSONField(default={})),
                ('url_status', models.CharField(default='CMN', max_length=5)),
                ('other_history', djongo.models.fields.JSONField(default={})),
                ('top_ratings', models.CharField(blank=True, default='-', max_length=5)),
                ('ratings_changed_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serp.groups')),
                ('fk_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serp.keyword')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'keywordhistory',
            },
        ),
    ]
