# Generated by Django 3.2.25 on 2025-09-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(error_messages={'unique': 'User with this email already exists.'}, max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('last_logout', models.DateTimeField(null=True, verbose_name='last logout')),
                ('last_home_visit', models.DateTimeField()),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('google_id', models.CharField(default='-', max_length=100)),
                ('account_status', models.CharField(default='normal', max_length=100)),
                ('normal_mode', models.CharField(default='enable', max_length=100)),
                ('social_mode', models.CharField(default='disable', max_length=100)),
                ('mail_count_status_no_keyword', models.IntegerField(default=0)),
                ('mail_no_keyword_routine', models.DateTimeField(auto_now_add=True)),
                ('designation', models.CharField(default='', max_length=35)),
                ('campaign', models.TextField(default='NA')),
                ('medium', models.TextField(default='NA')),
                ('source', models.TextField(default='NA')),
                ('referral', models.TextField(default='NA')),
                ('acc_type', models.CharField(choices=[('master', 'master'), ('admin', 'admin'), ('pivot', 'pivot')], default='pivot', max_length=50)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
