# Generated by Django 3.2.25 on 2026-08-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountusage',
            name='serp_depth',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='accountusage',
            name='serp_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='accountusage',
            name='serp_provider',
            field=models.CharField(default='datablue', max_length=50),
        ),
    ]
