# Generated by Django 3.2.25 on 2026-08-24 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serp', '0002_accountusage_byok_serp_key'),
    ]

    operations = [
        # Pre-existing drift: ClientAccount.password was widened from 30 to 128
        # to hold the PBKDF2 hash set_password() writes, but never migrated.
        # MongoDB does not enforce the length so nothing broke here; carried in
        # now so makemigrations stops regenerating it.
        migrations.AlterField(
            model_name='clientaccount',
            name='password',
            field=models.CharField(max_length=128),
        ),
        # The client portal's own credential. Before this, /client/login/
        # handed back the owner's authtoken Token.
        migrations.CreateModel(
            name='ClientToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serp.clientaccount')),
            ],
            options={
                'db_table': 'client_token',
            },
        ),
    ]
