# Generated by Django 3.2.25 on 2026-08-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serp', '0006_remove_client_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountusage',
            name='chatgpt_model',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='accountusage',
            name='claude_model',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='accountusage',
            name='gemini_model',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='accountusage',
            name='perplexity_model',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
