# Generated by Django 3.2.25 on 2026-09-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serp', '0008_refreshmanual_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='auto_call_status',
            field=models.CharField(default='avail', max_length=5),
        ),
    ]
