# Generated by Django 3.2.25 on 2026-09-02 18:37

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('serp', '0009_alter_keyword_auto_call_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='serp_advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='keyword',
            name='serp_features',
            field=djongo.models.fields.JSONField(default={}),
        ),
    ]
