# Generated by Django 3.2.25 on 2026-09-05 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0002_teamaccount_password_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamaccount',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
