"""
Django settings for SearchMirror.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

try:
    from datetime import date, datetime, timedelta
    from pathlib import Path
    import os

    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent

    GSC_CLIENT_ID = os.environ.get("GSC_CLIENT_ID", "")
    GSC_SECRET_ID = os.environ.get("GSC_SECRET_ID", "")
    GSC_REDIRECT_URL = os.environ.get("GSC_REDIRECT_URL", "")

    GA_CLIENT_ID = os.environ.get("GA_CLIENT_ID", "")
    GA_SECRET_ID = os.environ.get("GA_SECRET_ID", "")

    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    # The fallback is a committed literal: anyone with the repo can forge
    # sessions and signed values on an instance still using it. Fine for local
    # work, never with DEBUG off.
    SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or "django-insecure-xy#jxfza+ogsut_!i5x2)_ac!c4y@_c9@zm5cx$)n8b$%d&+sb"

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = os.environ.get("DJANGO_DEBUG", "").lower() == "true"

    UNSAFE_SECRET_KEYS = {
        "django-insecure-xy#jxfza+ogsut_!i5x2)_ac!c4y@_c9@zm5cx$)n8b$%d&+sb",
        "local-dev-only-not-a-real-secret",
        "change-me",
    }
    if not DEBUG and (SECRET_KEY in UNSAFE_SECRET_KEYS or len(SECRET_KEY) < 32):
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY is missing or still a development placeholder. Generate one: "
            'python -c "import secrets; print(secrets.token_urlsafe(50))"'
        )

    ALLOWED_HOSTS = (os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
                     if os.environ.get("DJANGO_ALLOWED_HOSTS") else []) + ["localhost", "127.0.0.1"]

    # The Django admin gives full cross-tenant model access. It is a
    # development convenience here, not a product surface: nothing in the app
    # routes a user to it. Off unless asked for, on automatically under DEBUG.
    # The obfuscated URL it used to sit behind is not a security control.
    ENABLE_DJANGO_ADMIN = (
        DEBUG or os.environ.get("ENABLE_DJANGO_ADMIN", "").lower() == "true"
    )

    # Application definition

    INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "rest_framework",
        "corsheaders",
        "rest_framework.authtoken",
        "rest_auth",
        "django_crontab",
        "account",
        "serp",
        "glassend",
        "mailend",
        "account.authorization",
        "competitor",
        "team_management",
        "contentmanager",
        "llmtracker",
    ]

    AUTH_USER_MODEL = "account.Account"

    REST_FRAMEWORK = {
        "EXCEPTION_HANDLER": "glassend.views.custom_exception_handler",
        "DEFAULT_AUTHENTICATION_CLASSES": (
            "account.authentication.OwnerOrTeamTokenAuthentication",
            "rest_framework.authentication.BasicAuthentication",
            "rest_framework.authentication.SessionAuthentication",
        ),
        "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    }

    JWT_AUTH = {
        # Authorization:Token xxx
        "JWT_AUTH_HEADER_PREFIX": "Token",
    }

    STATIC_ROOT = os.path.join(BASE_DIR, "static")
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    MEDIA_URL = "/media/"

    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        "corsheaders.middleware.CorsMiddleware",
        # Refuses any authenticated request naming a userid that is not the
        # caller's. Middleware and not a DRF permission on purpose: a view that
        # declares its own @permission_classes replaces the defaults entirely,
        # which is precisely how 56 views ended up with no ownership check at
        # all. See account/ownership.py.
        "account.ownership.UserIdOwnershipMiddleware",
    ]

    CRONJOBS = [
        ("30 23 */3 * *", "serp.register_token.user_reg_token_expiry"),
        # ("*/2 * * * *", "serp.report.report_schedule_emails", [None], {}, ">> " + str(BASE_DIR) + "/logs/cronjob.log 2>&1"),
        # ('15 */2 * * *', 'serp.automated_crons.currency_convert', [None], {}, '>> '+str(BASE_DIR)+'/logs/cronjob.log 2>&1'),
        # ("55 23 * * *", "serp.automated_crons.report_schedule_reset", [None], {}, ">> " + str(BASE_DIR) + "/logs/cronjob.log 2>&1"),
    ]

    # Was CORS_ORIGIN_ALLOW_ALL = True, which let any site on the internet make
    # cross-origin calls to this API. Tokens travel in the Authorization header
    # rather than a cookie, so a hostile page could not forge an authenticated
    # request -- but publishing an API that answers every origin is still not a
    # default to ship. Set CORS_ALLOWED_ORIGINS to your own front-end origins;
    # the fallback covers a local docker run only.
    CORS_ORIGIN_ALLOW_ALL = os.environ.get("CORS_ALLOW_ALL", "").lower() == "true"


    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # CSRF_COOKIE_HTTPONLY = True

    # Placeholder hosts and a previous operator's server IP used to be baked in
    # here. Comma-separated origins, each with its scheme.
    CORS_ORIGIN_WHITELIST = tuple(
        o.strip() for o in os.environ.get(
            "CORS_ALLOWED_ORIGINS",
            # Both spellings of the loopback host: on Windows "localhost"
            # resolves to ::1 first, so the browser may send either origin.
            # Listing one silently breaks CORS for half the machines.
            "http://localhost:3000,http://localhost:3001,http://localhost:8000,"
            "http://127.0.0.1:3000,http://127.0.0.1:3001,http://127.0.0.1:8000",
        ).split(",") if o.strip()
    )
    CORS_ALLOWED_ORIGINS = CORS_ORIGIN_WHITELIST

    # How long a browser may reuse one preflight. django-cors-headers already
    # defaults to this; it is pinned because /site-icon depends on it. Tokens
    # ride in the Authorization header, which is not a CORS-safelisted request
    # header, so every cross-origin icon is preceded by an OPTIONS -- and
    # /competitors asks for about 45 icons. Without a cached preflight that is
    # 45 extra round trips on every page load.
    CORS_PREFLIGHT_MAX_AGE = 86400

    ROOT_URLCONF = "tracker.urls"

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                ],
            },
        },
    ]

    WSGI_APPLICATION = "tracker.wsgi.application"

    # Database
    # https://docs.djangoproject.com/en/3.2/ref/settings/#databases

    # djongo memoises ONE MongoClient per database name for the life of the
    # process (djongo/database.py `clients`), but its _close() closes that
    # shared client. With the Django default of 0 the connection is closed
    # after every request, so the next request pulls the same dead client out
    # of the cache and reopening it resets the pymongo topology -- and server
    # selection cannot rescan sooner than MIN_HEARTBEAT_INTERVAL, 0.5s. That
    # was a flat ~500ms on EVERY authenticated request, work or no work.
    # Reuse the connection and the client is simply never closed.
    # Set to 0 to restore the old per-request behaviour.
    _CONN_MAX_AGE = os.environ.get("DB_CONN_MAX_AGE", "600").strip()
    _MONGO_POOL = os.environ.get("MONGO_MAX_POOL_SIZE", "100").strip()
    _MONGO_MAX_POOL = int(_MONGO_POOL) if _MONGO_POOL.isdigit() else 100
    DATABASES = {
        "default": {
            "ENGINE": "djongo",
            # djongo selects the database from NAME, not from the URI path —
            # they must agree or reads and writes land in different databases.
            "NAME": os.environ.get("MONGO_DB", "tracker"),
            "ENFORCE_SCHEMA": False,
            # Bounded rather than None: a finite age still recycles the
            # connection periodically, so a djongo bug that accumulates state
            # cannot run for the life of the worker.
            "CONN_MAX_AGE": int(_CONN_MAX_AGE) if _CONN_MAX_AGE.isdigit() else 600,
            "CLIENT": {
                "host": os.environ.get("MONGO_URI") or "mongodb://%s:%s@%s:%s/%s" % (
                    os.environ.get("MONGO_USER", "tracker"),
                    os.environ.get("MONGO_PASSWORD", "trackerlocal"),
                    os.environ.get("MONGO_HOST", "mongo"),
                    os.environ.get("MONGO_PORT", "27017"),
                    os.environ.get("MONGO_DB", "tracker")),
                # Django allocates one connection per thread and CONN_MAX_AGE
                # keeps them open, so one gunicorn process can hold as many
                # connections as it has threads. This must exceed GUNICORN_THREADS
                # (and ENGINE_THREADS) or requests queue inside pymongo.
                "maxPoolSize": _MONGO_MAX_POOL,
            },
        },
    }

    # Password validation
    # https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/3.2/howto/static-files/

    STATIC_URL = "/static/"

    # Default primary key field type
    # https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

    DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

    ################################### TIMEZONE SETTINGS STARTS ###################################

    # Internationalization
    # https://docs.djangoproject.com/en/3.2/topics/i18n/

    LANGUAGE_CODE = "en-us"

    DEF_LOCATION = "United States"

    TIME_ZONE = "Asia/Kolkata"

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True

    #################################### TIMEZONE SETTINGS ENDS ####################################
    #
    #
    #
    ################################## GENERAL APP SETTINGS STARTS ##################################
    TRIALDAYS = 14
    MAX_REPORTS_PER_PROJECT = 5

    # UNIQUE_KEYWORD_ID = 987654
    UNIQUE_KEYWORD_ID = 0

    SITE_URL = os.environ.get("APP_SITE_URL", "http://127.0.0.1:3001").rstrip("/")

    SERVICE_URL = os.environ.get("APP_API_URL", "http://127.0.0.1:8000").rstrip("/") + "/"

    SITE_SUB_URL = "/app/"

    PRICING_PLANS = str(BASE_DIR) + "/files/pricing_plans.json"

    ################################### GENERAL APP SETTINGS ENDS ###################################
    #
    #
    #
    ################################## EMAIL AUTHENTICATION STARTS ##################################

    EMAIL_HOST = os.environ.get("EMAIL_HOST", "")

    EMAIL_DELIVERY_MODE = "smtp" if EMAIL_HOST else "console"
    EMAIL_BACKEND = (
        "django.core.mail.backends.smtp.EmailBackend"
        if EMAIL_HOST
        else "django.core.mail.backends.console.EmailBackend"
    )

    EMAIL_USE_SSL = bool(EMAIL_HOST)

    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")

    HOST_MAIL = os.environ.get("HOST_MAIL", "SearchMirror <noreply@localhost>")

    ADMIN_MAIL = [a for a in os.environ.get("ADMIN_MAIL", "").split(",") if a.strip()]

    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

    EMAIL_PORT = 587

    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or HOST_MAIL

    ################################## EMAIL AUTHENTICATION ENDS ##################################
    #
    #
    #
    ################################## SEARCH VOLUME DEFAULT STARTS ##################################

    _DEFAULT_LOCATION_IDS = ["2840"]
    _DEFAULT_LANGUAGE_ID = "1000"

    PDAY_SVOLUME_GCOUNT = 7000
    FAIL_KW_UPDATE_CRON = 7
    UNWANT_SV_DELETE = 100

    ################################## SEARCH VOLUME DEFAULT ENDS ##################################
    #
    #
    #
    #################################### GOOGLE TOKEN STARTS ####################################


    #################################### GOOGLE TOKEN ENDS ####################################
    #
    #
    #
    #################################### OPENAI API KEY - STARTS ####################################

    OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")

    ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
    PERPLEXITY_API_KEY = os.environ.get("PERPLEXITY_API_KEY", "")
    GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")

    #################################### OPENAI API KEY - ENDS ####################################

except Exception:
    # A partial settings module is never a usable fallback. Surface the real
    # import/configuration error so containers fail their startup checks.
    raise
