export default function useSkeletonRows() {
   const rows = [
         {
            id: 1,
            platform: "mobile",
            keyword: 'Tracker',
            volume: '25000',
            region: "US",
            volumemark: "UP",
            positionmark: "DOWN",
            position: '19',
         }, {
            id: 2,
            platform: "mobile",
            keyword: 'Hotstar',
            volume: '25000',
            region: "AU",
            volumemark: "UP",
            positionmark: "UP",
            position: '18',
         }, {
            id: 3,
            platform: "mobile",
            keyword: 'Letgo clone script download from Example official website',
            volume: '9980000',
            region: "GB",
            volumemark: "DOWN",
            positionmark: "DOWN",
            position: '11',
         }, {
            id: 4,
            platform: "desktop",
            keyword: 'Swiss',
            volume: '120000',
            region: "AU",
            volumemark: "UP",
            positionmark: "DOWN",
            position: '15',
         }, {
            id: 5,
            platform: "mobile",
            keyword: 'Ferrari',
            volume: '10000',
            region: "US",
            volumemark: "UP",
            positionmark: "UP",
            position: '17',
         }, {
            id: 6,
            platform: "desktop",
            keyword: 'Adidas',
            volume: '80',
            region: "AS",
            volumemark: "DOWN",
            positionmark: "DOWN",
            position: '98',
         }, {
            id: 7,
            platform: "mobile",
            keyword: 'Titan',
            volume: '89',
            region: "US",
            volumemark: "UP",
            positionmark: "DOWN",
            position: '45',
         },  {
            id: 8,
            platform: "desktop",
            keyword: 'Mercedes',
            volume: '0',
            region: "IR",
            volumemark: "UP",
            positionmark: "UP",
            position: '77',
         }, {
            id: 9,
            platform: "mobile",
            keyword: 'Audi',
            volume: '100000', 
            region: "US",
            volumemark: "UP",
            positionmark: "UP",
            position: '78',
         }, {
            id: 10,
            platform: "desktop",
            keyword: 'Amway',
            volume: '5000',
            region: "US",
            volumemark: "UP",
            positionmark: "DOWN",
            position: '68',
         }, {
            id: 11,
            platform: "mobile",
            keyword: 'Tracker 1', 
            volume: '25000',
            region: "US",
            volumemark: "DOWN",
            positionmark: "UP",
            position: '19',
         }, {
            id: 12,
            platform: "desktop",
            keyword: 'Hotstar 1',
            volume: '25000',
            region: "IN",
            volumemark: "UP",
            positionmark: "DOWN",
            position: '18',
         }, {
            id: 13,
            platform: "mobile",
            keyword: 'Rolex 1',
            volume: '50000',
            region: "US",
            volumemark: "UP",
            positionmark: "DOWN",
            position: '11',
         }, {
            id: 14,
            platform: "desktop",
            keyword: 'Swiss 1',
            volume: '120000',
            region: "US",
            volumemark: "UP",
            positionmark: "DOWN",
            position: '15',
         }, {
            id: 15,
            platform: "desktop",
            keyword: 'Ferrari 1',
            volume: '10000',
            region: "US",
            volumemark: "UP",
            positionmark: "DOWN",
            position: '17',
         }, {
            id: 16,
            platform: "desktop",
            keyword: 'Adidas 1',
            volume: '80',
            region: "ID",
            volumemark: "DOWN",
            positionmark: "UP",
            position: '98',
         }, {
            id: 17,
            platform: "mobile",
            keyword: 'Titan 1',
            volume: '89',
            region: "US",
            volumemark: "UP",
            positionmark: "DOWN",
            position: '45',
         },  {
            id: 18,
            platform: "mobile",
            keyword: 'Mercedes 1',
            volume: '0',
            region: "US",
            volumemark: "UP",
            positionmark: "DOWN", 
            position: '77',
         }, {
            id: 19,
            platform: "desktop",
            keyword: 'Audi 1',
            volume: '100000',
            region: "AR",
            volumemark: "UP",
            positionmark: "DOWN",
            position: '78',
         }, {
            id: 20,
            platform: "mobile",
            keyword: 'Amway 1',
            volume: '5000',
            region: "US",
            volumemark: "UP",
            positionmark: "DOWN",
            position: '68',
         },
      ];

   return rows;
}
