# Generated by Django 3.2.25 on 2025-09-24 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMPrompt',
            fields=[
                ('prompt_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('track_status', models.CharField(choices=[('INIT', 'Initialized'), ('SCHD', 'Scheduled'), ('DONE', 'Completed'), ('FAIL', 'Failed')], default='INIT', max_length=4)),
                ('track_message', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serp.groups')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'llm_prompts',
            },
        ),
        migrations.CreateModel(
            name='LLMPromptAnalytics',
            fields=[
                ('analytics_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(choices=[('ChatGPT', 'ChatGPT'), ('Gemini', 'Gemini'), ('Claude', 'Claude'), ('Perplexity', 'Perplexity'), ('DeepSeek', 'DeepSeek')], max_length=20)),
                ('track_status', models.CharField(choices=[('INIT', 'Initialized'), ('SCHD', 'Scheduled'), ('DONE', 'Completed'), ('FAIL', 'Failed')], default='INIT', max_length=4)),
                ('track_message', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('is_mention', models.BooleanField(default=False, help_text='Whether this prompt is a mention')),
                ('mention_count', models.IntegerField(default=0, help_text='Number of mentions')),
                ('citations', djongo.models.fields.JSONField(blank=True, default=list, help_text='List of citation URLs')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], default='neutral', help_text='Sentiment classification', max_length=10)),
                ('sentiment_score', models.FloatField(default=0.0, help_text='Sentiment score (-1.0 to 1.0)')),
                ('context_summary', models.TextField(blank=True, help_text='Summary of the context', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fk_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='llmtracker.llmprompt')),
            ],
            options={
                'db_table': 'llm_prompt_analytics',
            },
        ),
    ]
