# Generated by Django 3.2.25 on 2026-08-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmpromptanalytics',
            name='response_text',
            field=models.TextField(blank=True, help_text='Full model response text', null=True),
        ),
    ]
