# Generated by Django 3.2.25 on 2026-08-30 13:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('serp', '0007_auto_20260830_1920'),
        ('llmtracker', '0002_llmpromptanalytics_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmpromptanalytics',
            name='position_score',
            field=models.FloatField(default=0.0, help_text='How prominently the brand appears in the answer, 0..1 (earlier = higher)'),
        ),
        migrations.CreateModel(
            name='LLMMetricSnapshot',
            fields=[
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('prompts_measured', models.IntegerField(default=0)),
                ('mention_rate', models.FloatField(default=0.0, help_text='Fraction of measured model answers that mention the brand, 0..1')),
                ('avg_sentiment', models.FloatField(default=0.0, help_text='Mean sentiment score across mentioning answers, -1..1')),
                ('avg_position', models.FloatField(default=0.0, help_text='Mean prominence (position_score) across mentioning answers, 0..1')),
                ('total_citations', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_snapshots', to='serp.groups')),
            ],
            options={
                'db_table': 'llm_metric_snapshot',
            },
        ),
    ]
