# Generated by Django 3.2.25 on 2026-09-02 17:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('serp', '0009_alter_keyword_auto_call_status'),
        ('llmtracker', '0003_auto_20260830_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCompetitor',
            fields=[
                ('competitor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Brand name as it appears in answers', max_length=120)),
                ('url', models.CharField(blank=True, default='', help_text='Optional site, so the domain counts as a mention too', max_length=255)),
                ('source', models.CharField(choices=[('detected', 'Detected from answers'), ('user', 'Added by user')], default='detected', max_length=8)),
                ('is_tracked', models.BooleanField(default=True, help_text='Scored against answers; false retires it without deleting')),
                ('detected_answers', models.IntegerField(default=0, help_text='Answers this name was detected in when it was proposed')),
                ('detected_mentions', models.IntegerField(default=0, help_text='Occurrences across those answers when it was proposed')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_competitors', to='serp.groups')),
            ],
            options={
                'db_table': 'llm_competitors',
            },
        ),
        migrations.CreateModel(
            name='LLMCompetitorAnalytics',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_mentioned', models.BooleanField(default=False)),
                ('mention_count', models.IntegerField(default=0, help_text='Occurrences in this answer, overlapping matches merged')),
                ('first_index', models.IntegerField(default=-1, help_text='Character offset of the first occurrence; -1 when absent')),
                ('position_score', models.FloatField(default=0.0, help_text='How prominently the rival appears, 0..1 (earlier = higher)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fk_analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_analytics', to='llmtracker.llmpromptanalytics')),
                ('fk_competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='llmtracker.llmcompetitor')),
            ],
            options={
                'db_table': 'llm_competitor_analytics',
            },
        ),
    ]
